### ISSUE TITLE
This repo (volttron-lib-dnp3-driver) is not operable: clone, fork, etc.

### ISSUE THREAD

**Issue by kefeimo** [eclipse-volttron/volttron-lib-dnp3-driver#2]
![image](https://user-images.githubusercontent.com/28743873/223485647-5cbebf6a-c427-4c7b-8378-d3489b71c7ad.png)

**Comment by craigpnnl** [comment]
@schandrika pushed a readme into the repo.  I suppose that makes this available for you to continue to work from.
